## YAML Template.
language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
services:
- mysql
- docker
dist: trusty
sudo: required
addons:
  apt:
  packages:
  - mysql-server-5.7
  - mysql-client-core-5.7
  - mysql-client-5.7
before_script:
- mysql -u root -e 'CREATE DATABASE empleado;'
- mysql -u root -e "CREATE USER 'sa'@'localhost' IDENTIFIED BY 'sa';"
- mysql -u root -e "GRANT ALL ON empleado.* TO 'sa'@'localhost';"
before_install:
# install heroku CLI
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- chmod +x mvnw
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
script:
- cd bootdocker
- docker build -t danielaocampo/empleado-back .
- docker tag danielaocampo/empleado-back registry.heroku.com/$HEROKU_APP_NAME/web
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: empleado123